### ISSUE TITLE
COT-Error: too few genes, failed in p-value estimation!

### ISSUE THREAD

**Issue by bio-visualisation** [MintaYLu/COT#8]
Hi, 
I encountered this problem when I ran "cot.estimate_p_values()". It showed too few genes, failed in p-value estimation!. Is there any way to overcome this? Although it is clearly mentioned in the manuscript that sub-type-specific marker gene (SMG) is stringent than differentially expressed genes, I am still wondering whether we are loosing biologically meaningful markers with mathematical stringency.
Thank you.

**Comment by MintaYLu** [comment]
Hello,

Thanks for the follow-up, 

> I encountered this problem when I ran "cot.estimate_p_values()". It showed too few genes, failed in p-value estimation!. Is there any way to overcome this? Although it is clearly mentioned in the manuscript that sub-type-specific marker gene (SMG) is stringent than differentially expressed genes, I am still wondering whether we are loosing biologically meaningful markers with mathematical.

When performing the p-value estimation, a pre-processing step is to separate the `n` genes into `k` clusters, where `n` and `k` are the number of genes and subtypes, respectively (please see the class function [estimate_p_values](https://github.com/MintaYLu/COT/blob/aa9d671181945e1eb09082f2d261c5f78894b7b2/COT/COT.py#L74) for details). Therefore, we must ensure that `n >= k`, and ideally, `n >> k` is preferred since later the histogram of `COT` will be fitted to `k` Gaussian functions. Based on this, in order to use `cot.estimate_p_values()`, please either increase the number of genes or decrease the number of subtypes in your data.

Hope it helps! Please feel free to contact us if you have additional questions.

Best,

**Comment by bio-visualisation** [comment]
I had three subtypes. I reduced to two subtypes. but the result is same. I am not sure how to increase the number of genes.

**Comment by MintaYLu** [comment]
> I had three subtypes. I reduced to two subtypes. but the result is same. I am not sure how to increase the number of genes.

Hello, 
Thanks for reaching out.
Can you please provide more details of your dataset? We would recommend you have at least 100 genes for p-value estimation. If the gene number is relatively small, please use COT generated cosine value directly, instead of the estimated p-value. The marker genes come with the bigger the COT cosine value.
Hope it helps!
Best,
